import Head from 'next/head';

import { Title } from 'ui/Title';

import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next.Js Turbo Boilerplate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center py-16">
        <Title>
          Next.Js <span className="text-indigo-500">Turbo</span> Boilerplate
        </Title>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          Powered by the greatest technologies of today
        </div>
      </main>
    </>
  );
};

export default Home;
