version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - '*'
    assignees:
      - 'alex289'
    reviewers:
      - 'alex289'

  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'monthly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'db'
      - dependency-name: 'ui'
    assignees:
      - 'alex289'
    reviewers:
      - 'alex289'

  - package-ecosystem: 'npm'
    directory: '/packages/db'
    schedule:
      interval: 'monthly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - '*'
    assignees:
      - 'alex289'
    reviewers:
      - 'alex289'

  - package-ecosystem: 'npm'
    directory: '/packages/ui'
    schedule:
      interval: 'monthly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - '*'
    assignees:
      - 'alex289'
    reviewers:
      - 'alex289'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - '*'
    assignees:
      - 'alex289'
    reviewers:
      - 'alex289'
