name: Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      assignee: alex289
      baseBranch: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Update dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u
          cd apps/web && ncu -x db,ui -u
          cd ../../packages/db && ncu -u
          cd ../ui && ncu -u
          cd ../../ && pnpm install --no-frozen-lockfile

      - name: Check for changes
        id: changes
        run: |
          git_status=$(git status --porcelain)
          if [ -n "$git_status" ]; then
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Get current date
        if: env.changes == 'true'
        id: date
        run: echo "date=$(date +'%d_%m_%Y')" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'update/${{ env.date }}'
          labels: dependencies
          delete-branch: true
          commit-message: 'chore: Update dependencies'
          assignees: ${{ env.assignee }}
          base: ${{ env.baseBranch }}
          title: 'Automatic Package Update ${{ env.date }}'
          body: This pull request includes updates for all nodejs dependencies in the project.
